-- ========================================================================
-- ⚠️ VERALTETE VERSION - BITTE VERWENDE sample-data-v2.sql
-- ========================================================================
-- Diese Datei ist veraltet und verwendet die alte Datenbankstruktur.
-- 
-- BITTE VERWENDE STATTDESSEN:
-- → database-schema.sql (für das Schema)
-- → sample-data-v2.sql (für Demo-Daten)
--
-- MIGRATION: Siehe MIGRATION_GUIDE.md für Anleitungen zum Upgrade
-- ========================================================================

-- Die alte Struktur hatte folgende Unterschiede:
-- - difficulty als varchar ('easy', 'medium', 'hard') statt int (1-5)
-- - Keine prep_time, cook_time, total_time Felder
-- - Keine servings Spalte
-- - Keine user_preferences oder user_favorites Tabellen

-- ========================================================================
-- NÄCHSTE SCHRITTE:
-- ========================================================================
-- 1. Führe database-schema.sql aus, um das neue Schema zu erstellen
-- 2. Führe sample-data-v2.sql aus, um Demo-Daten einzufügen
-- 3. Siehe DATENBANK_SETUP_V2.md für vollständige Dokumentation
-- ========================================================================
